include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    sort_constructors_first: true
    use_super_parameters: true
    unnecessary_lambdas: true
    avoid_redundant_argument_values: true
    always_declare_return_types: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
