name: gamewheel
description: "A game selection wheel"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_fortune_wheel: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

# to run, use dart run flutter_launcher_icons:main
flutter_launcher_icons:
  image_path: 'assets/images/logo.png'
  adaptive_icon_foreground: 'assets/images/logo.png'
  adaptive_icon_background: '#011C3C'
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: 'assets/images/logo.png'
    background_color: '#011C3C'
    theme_color: '#011C3C'
  windows:
    generate: true
    image_path: 'assets/images/logo.png'
    icon_size: 48

# to run, use dart run flutter_native_splash:create
flutter_native_splash:
  background_image: 'assets/images/logo.png'
  android_12:
    image: 'assets/images/logo.png'
    color: "#011C3C"
    icon_background_color: "#011C3C"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Genos
      fonts:
        - asset: assets/fonts/Genos-Bold.ttf
          weight: 700
        - asset: assets/fonts/Genos-Italic.ttf
          style: italic
        - asset: assets/fonts/Genos-Regular.ttf
